services:
  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    container_name: order-processing-application
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      # Note: We use the service name 'order-db' as the hostname
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/orders
      - SPRING_DATASOURCE_USERNAME=orders
      - SPRING_DATASOURCE_PASSWORD=orders
    depends_on:
      order-db:
        condition: service_healthy

  order-db:
    image: postgres:16-alpine
    container_name: order-processing-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    volumes:
      - order-processing-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orders" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  order-processing-pgdata:
